export const config = {
	REACT_APP_FIREBASE_API_KEY: process.env.REACT_APP_FIREBASE_API_KEY,
	REACT_APP_FIREBASE_AUTH_DOMAIN: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
	REACT_APP_FIREBASE_PROJECT_ID: process.env.REACT_APP_FIREBASE_PROJECT_ID,
	REACT_APP_FIREBASE_STORAGE_BUCKET: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
	REACT_APP_FIREBASE_MESSAGING_SENDER_ID: process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
	REACT_APP_FIREBASE_APP_ID: process.env.REACT_APP_FIREBASE_APP_ID,
	REACT_APP_FIREBASE_MEASUREMENT_ID: process.env.REACT_APP_FIREBASE_MEASUREMENT_ID,
	REACT_APP_DIGITAL_OCEAN_KEY: process.env.REACT_APP_DIGITAL_OCEAN_KEY,
	REACT_APP_DIGITAL_OCEAN_SECRET: process.env.REACT_APP_DIGITAL_OCEAN_SECRET,
	REACT_APP_BUCKET_NAME: process.env.REACT_APP_BUCKET_NAME,
	REACT_APP_BUCKET_REGION: process.env.REACT_APP_BUCKET_REGION
};
